In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import json
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import HateSpeechClassifier
import pickle

/home/marisa/.local/lib/python3.6/site-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.04.1 is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,


In [15]:
from imp import reload
reload(HateSpeechClassifier)

<module 'HateSpeechClassifier' from '/mnt/c/Users/maris/OneDrive - Rhodes College/Documents/2021-2022/2022, Spring/COMP486/CounterSpeechGenerator/HateSpeechClassifier/HateSpeechClassifier.py'>

##### Kfold Validation

In [3]:
combined_data_path = 'Data/combined_data.csv'

with open(combined_data_path, 'r', encoding='utf8') as f:
    combined = pd.read_csv(f).to_dict()

tweets = [] # these arrays are aligned by index; tweet[i] has label[i]
labels = []
for tweet, label in zip(combined['HATE_SPEECH'].values(), combined['CLASS'].values()):
    tweet = HateSpeechClassifier.utils_preprocess_text(tweet) #, lst_stopwords=stop_words)
    tweets.append(tweet)
    labels.append(int(label))

In [4]:
embedding_types = ['word2vec', 'glove']
#model_types = ['LR']
weighting = 'tfidf'
dimensions=300

In [ ]:
df = HateSpeechClassifier.run_tests_kfold(tweets, labels, 
                                          weighting_type=weighting,
                                          embedding_types=embedding_types,
                                          with_stopwords=True
                                          #model_types=model_types
                                          )

In [6]:
df.to_excel('Reports/kfold_results_missing_stop.xlsx')

Training full models:

In [23]:
HateSpeechClassifier.train_and_save(tweets, labels, 
                                    weighting_type=weighting,
                                    embedding_types=embedding_types,
                                    with_stopwords=True
                                    #model_types=model_types
                                    )

----------------------------------------
bert


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[23:23:34] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [27]:
HateSpeechClassifier.train_and_save(tweets, labels, 
                                    embedding_types=['bert']
                                    #model_types=model_types
                                    )

----------------------------------------
bert


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:06:52] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [28]:
HateSpeechClassifier.train_and_save(tweets, labels, 
                                    weighting_type='equal',
                                    embedding_types=['tfidf', 'doc2vec', 'word2vec', 'glove'],
                                    with_stopwords=True
                                    #model_types=model_types
                                    )

----------------------------------------
tfidf
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:10:44] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
----------------------------------------
doc2vec
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:13:54] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
----------------------------------------
word2vec
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:18:29] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
----------------------------------------
glove
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:21:54] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [29]:
HateSpeechClassifier.train_and_save(tweets, labels, 
                                    weighting_type='equal',
                                    embedding_types=['tfidf', 'doc2vec', 'word2vec', 'glove'],
                                    with_stopwords=False,
                                    model_types=['DT', 'SVM', 'XGB']
                                    )

----------------------------------------
tfidf
  DT
  SVM
  XGB
[08:24:41] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


----------------------------------------
doc2vec
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:27:40] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
----------------------------------------
word2vec
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:32:21] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
----------------------------------------
glove
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:35:08] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [3]:
HateSpeechClassifier.train_and_save(tweets, labels, 
                                    weighting_type='tfidf',
                                    embedding_types=['word2vec', 'glove'],
                                    with_stopwords=True
                                    #model_types=model_types
                                    )

----------------------------------------
word2vec
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:48:30] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
----------------------------------------
glove
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:53:05] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [4]:
HateSpeechClassifier.train_and_save(tweets, labels, 
                                    weighting_type='tfidf',
                                    embedding_types=['word2vec', 'glove'],
                                    with_stopwords=False
                                    #model_types=model_types
                                    )

----------------------------------------
word2vec
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[08:58:20] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
----------------------------------------
glove
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[09:04:05] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [17]:
df

fit_time  score_time  test_accuracy  test_balanced_accuracy  \
0     6.419888    0.138435       0.940022                0.857605   
1     2.099215    0.036161       0.936170                0.857619   
2     2.006598    0.065954       0.935079                0.853686   
3     1.892668    0.090981       0.940535                0.841424   
4     1.833052    0.037889       0.938352                0.850503   
..         ...         ...            ...                     ...   
70  150.783504    0.090663       0.941112                0.869464   
71  166.480607    0.105030       0.951446                0.883369   
72  147.113061    0.096916       0.955265                0.899293   
73  147.343336    0.116747       0.944354                0.850405   
74  149.041375    0.078618       0.948172                0.869929   

    test_precision_weighted  test_recall_weighted  test_f1_weighted  \
0                  0.940794              0.940022          0.935164   
1                  0.937053              0.936170          0.931659   
2                  0.933566              0.935079          0.931443   
3                  0.940458              0.940535          0.935824   
4                  0.938752              0.938352          0.932406   
..                      ...                   ...               ...   
70                 0.940354              0.941112          0.939413   
71                 0.952430              0.951446          0.949104   
72                 0.955002              0.955265          0.953857   
73                 0.943454              0.944354          0.941278   
74                 0.946471              0.948172          0.945343   

    test_roc_auc_ovr                        model  
0           0.987865  LR_w2v_equalweight_withstop  
1           0.991486  LR_w2v_equalweight_withstop  
2           0.985958  LR_w2v_equalweight_withstop  
3           0.985225  LR_w2v_equalweight_withstop  
4           0.990855  LR_w2v_equalweight_withstop  
..               ...                          ...  
70          0.992571            XGB_bert_withstop  
71          0.994659            XGB_bert_withstop  
72          0.993419            XGB_bert_withstop  
73          0.988166            XGB_bert_withstop  
74          0.990897            XGB_bert_withstop  

[75 rows x 9 columns]

In [ ]:
confusions = {}

In [ ]:
with open('confusions.json', 'w') as f:
    json.dump(confusions, f)

In [ ]:
filetype = 'png'
for model_name, confusion in confusions.items():
    plt.subplots(tight_layout=True)
    fig = sns.heatmap(confusion, vmax=817.0, annot=True, fmt='g', xticklabels=HateSpeechClassifier.TARGET_TYPES, yticklabels=HateSpeechClassifier.TARGET_TYPES)
    fig.set_xlabel('Predicted')
    fig.set_ylabel('Actual')

    plt.savefig(f'Figures/Confusion_{model_name}.{filetype}')

Getting metrics for tfidf and doc2vec:

In [6]:
X_train, X_test, y_train, y_test = train_test_split(tweets, labels, random_state=100, test_size=0.1)

In [8]:
# train on split
HateSpeechClassifier.train_and_save(X_train, y_train,
                                    embedding_types=['tfidf', 'doc2vec'])

----------------------------------------
tfidf
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[10:29:55] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
----------------------------------------
doc2vec
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[10:33:42] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [9]:
HateSpeechClassifier.train_and_save(X_train, y_train,
                                    embedding_types=['tfidf', 'doc2vec'],
                                    with_stopwords=True)

----------------------------------------
tfidf
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[10:37:41] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
----------------------------------------
doc2vec
  LR
  RF
  DT
  SVM
  XGB


/home/marisa/.local/lib/python3.6/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[10:41:02] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [4]:
import os

In [5]:
model_names = os.listdir(HateSpeechClassifier.MODELS_PATH)
model_names.remove('desktop.ini')
model_names.remove('test_split_d2v_tfidf')

In [14]:
model_names = ['DT_bert_nostop',
 'DT_bert_withstop',
 'DT_d2v_100epochs_300dim_nostop',
 'DT_d2v_100epochs_300dim_withstop',
 'DT_glove_300dim_equalweight_nostop',
 #'DT_glove_300dim_equalweight_withstop',
 #'DT_glove_300dim_tfidfweight_nostop',
 #'DT_glove_300dim_tfidfweight_withstop',
 'DT_tfidf_matrix_nostop',
 'DT_tfidf_matrix_withstop',
 'DT_w2v_equalweight_nostop',
 'DT_w2v_equalweight_withstop',
 #'DT_w2v_tfidfweight_nostop',
 #'DT_w2v_tfidfweight_withstop',
 'LR_bert_nostop',
 'LR_bert_withstop',
 'LR_d2v_100epochs_300dim_nostop',
 'LR_d2v_100epochs_300dim_withstop',
 'LR_glove_300dim_equalweight_nostop',
 #'LR_glove_300dim_equalweight_withstop',
 #'LR_glove_300dim_tfidfweight_nostop',
 #'LR_glove_300dim_tfidfweight_withstop',
 'LR_tfidf_matrix_nostop',
 'LR_tfidf_matrix_withstop',
 'LR_w2v_equalweight_nostop',
 'LR_w2v_equalweight_withstop',
 #'LR_w2v_tfidfweight_nostop',
 #'LR_w2v_tfidfweight_withstop',
 'RF_bert_nostop',
 'RF_bert_withstop',
 'RF_d2v_100epochs_300dim_nostop',
 'RF_d2v_100epochs_300dim_withstop',
 'RF_glove_300dim_equalweight_nostop',
 #'RF_glove_300dim_equalweight_withstop',
 #'RF_glove_300dim_tfidfweight_nostop',
 #'RF_glove_300dim_tfidfweight_withstop',
 'RF_tfidf_matrix_nostop',
 'RF_tfidf_matrix_withstop',
 'RF_w2v_equalweight_nostop',
 'RF_w2v_equalweight_withstop',
 #'RF_w2v_tfidfweight_nostop',
 #'RF_w2v_tfidfweight_withstop',
 'SVM_bert_nostop',
 'SVM_bert_withstop',
 'SVM_d2v_100epochs_300dim_nostop',
 'SVM_d2v_100epochs_300dim_withstop',
 'SVM_glove_300dim_equalweight_nostop',
 #'SVM_glove_300dim_equalweight_withstop',
 #'SVM_glove_300dim_tfidfweight_nostop',
 #'SVM_glove_300dim_tfidfweight_withstop',
 'SVM_tfidf_matrix_nostop',
 'SVM_tfidf_matrix_withstop',
 'SVM_w2v_equalweight_nostop',
 'SVM_w2v_equalweight_withstop',
 #'SVM_w2v_tfidfweight_nostop',
 #'SVM_w2v_tfidfweight_withstop',
 'XGB_bert_nostop',
 'XGB_bert_withstop',
 'XGB_d2v_100epochs_300dim_nostop',
 'XGB_d2v_100epochs_300dim_withstop',
 'XGB_glove_300dim_equalweight_nostop',
 #'XGB_glove_300dim_equalweight_withstop',
 #'XGB_glove_300dim_tfidfweight_nostop',
 #'XGB_glove_300dim_tfidfweight_withstop',
 'XGB_tfidf_matrix_nostop',
 'XGB_tfidf_matrix_withstop',
 'XGB_w2v_equalweight_nostop',
 'XGB_w2v_equalweight_withstop'
 #'XGB_w2v_tfidfweight_nostop',
 #'XGB_w2v_tfidfweight_withstop'
 ]

In [7]:
with open('Data/reddit_hate.json', 'r') as f:
    reddit_hate = json.load(f)
with open('Data/reddit_none.json', 'r') as f:
    reddit_none = json.load(f)
with open('Data/tumblr_hate.json', 'r') as f:
    tumblr_all = json.load(f)

In [8]:
reddit_posts = []
reddit_targets = []

for post_num in reddit_hate:
    text = reddit_hate[post_num]['text']
    target = reddit_hate[post_num]['target']

    reddit_posts.append(text)
    reddit_targets.append(target)

for post_num in reddit_none:
    text = reddit_none[post_num]['text']
    target = reddit_none[post_num]['target']

    reddit_posts.append(text)
    reddit_targets.append(target)

In [9]:
tumblr_posts = []
tumblr_targets = []

for post_num in tumblr_all:
    text = tumblr_all[post_num]['text']
    target = tumblr_all[post_num]['target']

    tumblr_posts.append(text)
    tumblr_targets.append(target)

In [10]:
all_posts = reddit_posts + tumblr_posts
all_targets = reddit_targets + tumblr_targets

In [11]:
X_test = all_posts
y_test = [HateSpeechClassifier.TARGET_TO_INDEX[target] for target in all_targets]

In [15]:
#model_names = ['LR_tfidf_matrix_nostop', 'RF_tfidf_matrix_nostop', 'DT_tfidf_matrix_nostop', 'SVM_tfidf_matrix_nostop', 'XGB_tfidf_matrix_nostop',
#               'LR_tfidf_matrix_withstop', 'RF_tfidf_matrix_withstop', 'DT_tfidf_matrix_withstop', 'SVM_tfidf_matrix_withstop', 'XGB_tfidf_matrix_withstop',
#               'LR_d2v_100epochs_300dim_nostop', 'RF_d2v_100epochs_300dim_nostop', 'DT_d2v_100epochs_300dim_nostop', 'SVM_d2v_100epochs_300dim_nostop', 'XGB_d2v_100epochs_300dim_nostop',
#               'LR_d2v_100epochs_300dim_withstop', 'RF_d2v_100epochs_300dim_withstop', 'DT_d2v_100epochs_300dim_withstop', 'SVM_d2v_100epochs_300dim_withstop', 'XGB_d2v_100epochs_300dim_withstop']
results = HateSpeechClassifier.run_tests(X_test, y_test, model_names)

----------------------------------------
DT_bert_nostop


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Accuracy: 47.16417910447761
{'0': {'precision': 0.1111111111111111, 'recall': 0.05263157894736842, 'f1-score': 0.07142857142857142, 'support': 19}, '1': {'precision': 0.2857142857142857, 'recall': 0.1111111111111111, 'f1-score': 0.16, 'support': 18}, '2': {'precision': 0.3333333333333333, 'recall': 0.09090909090909091, 'f1-score': 0.14285714285714288, 'support': 22}, '3': {'precision': 0.23076923076923078, 'recall': 0.14285714285714285, 'f1-score': 0.17647058823529413, 'support': 21}, '4': {'precision': 0.05263157894736842, 'recall': 0.05555555555555555, 'f1-score': 0.05405405405405406, 'support': 18}, '5': {'precision': 0.1111111111111111, 'recall': 0.05, 'f1-score': 0.06896551724137932, 'support': 20}, '6': {'precision': 0.1111111111111111, 'recall': 0.09523809523809523, 'f1-score': 0.10256410256410256, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.5816733067729084, 'recall': 0.8295454545454546, 'f1-score': 0.683840749414

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Accuracy: 40.8955223880597
{'0': {'precision': 0.2222222222222222, 'recall': 0.10526315789473684, 'f1-score': 0.14285714285714285, 'support': 19}, '1': {'precision': 0.125, 'recall': 0.1111111111111111, 'f1-score': 0.11764705882352941, 'support': 18}, '2': {'precision': 0.17142857142857143, 'recall': 0.2727272727272727, 'f1-score': 0.21052631578947367, 'support': 22}, '3': {'precision': 0.3125, 'recall': 0.23809523809523808, 'f1-score': 0.27027027027027023, 'support': 21}, '4': {'precision': 0.19230769230769232, 'recall': 0.2777777777777778, 'f1-score': 0.2272727272727273, 'support': 18}, '5': {'precision': 0.10526315789473684, 'recall': 0.1, 'f1-score': 0.10256410256410256, 'support': 20}, '6': {'precision': 0.1724137931034483, 'recall': 0.23809523809523808, 'f1-score': 0.19999999999999998, 'support': 21}, '7': {'precision': 0.2222222222222222, 'recall': 0.2, 'f1-score': 0.2105263157894737, 'support': 20}, '8': {'precision': 0.6347305389221557, 'recall': 0.6022727272727273, 'f1-score'

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and 

Accuracy: 59.40298507462687
{'0': {'precision': 1.0, 'recall': 0.21052631578947367, 'f1-score': 0.34782608695652173, 'support': 19}, '1': {'precision': 0.6666666666666666, 'recall': 0.2222222222222222, 'f1-score': 0.3333333333333333, 'support': 18}, '2': {'precision': 0.4444444444444444, 'recall': 0.18181818181818182, 'f1-score': 0.2580645161290322, 'support': 22}, '3': {'precision': 0.5294117647058824, 'recall': 0.42857142857142855, 'f1-score': 0.4736842105263158, 'support': 21}, '4': {'precision': 0.631578947368421, 'recall': 0.6666666666666666, 'f1-score': 0.6486486486486486, 'support': 18}, '5': {'precision': 0.8, 'recall': 0.2, 'f1-score': 0.32000000000000006, 'support': 20}, '6': {'precision': 0.38095238095238093, 'recall': 0.38095238095238093, 'f1-score': 0.38095238095238093, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.6062992125984252, 'recall': 0.875, 'f1-score': 0.7162790697674419, 'support': 176}, 'accuracy': 0

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Accuracy: 59.70149253731343
{'0': {'precision': 1.0, 'recall': 0.15789473684210525, 'f1-score': 0.2727272727272727, 'support': 19}, '1': {'precision': 0.6153846153846154, 'recall': 0.4444444444444444, 'f1-score': 0.5161290322580646, 'support': 18}, '2': {'precision': 0.47058823529411764, 'recall': 0.36363636363636365, 'f1-score': 0.41025641025641024, 'support': 22}, '3': {'precision': 0.5833333333333334, 'recall': 0.6666666666666666, 'f1-score': 0.6222222222222222, 'support': 21}, '4': {'precision': 0.6111111111111112, 'recall': 0.6111111111111112, 'f1-score': 0.6111111111111112, 'support': 18}, '5': {'precision': 0.6363636363636364, 'recall': 0.35, 'f1-score': 0.45161290322580644, 'support': 20}, '6': {'precision': 0.2978723404255319, 'recall': 0.6666666666666666, 'f1-score': 0.4117647058823529, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.6818181818181818, 'recall': 0.7670454545454546, 'f1-score': 0.7219251336898397, 'su

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 57.611940298507456
{'0': {'precision': 0.5, 'recall': 0.10526315789473684, 'f1-score': 0.17391304347826086, 'support': 19}, '1': {'precision': 0.8333333333333334, 'recall': 0.5555555555555556, 'f1-score': 0.6666666666666667, 'support': 18}, '2': {'precision': 0.3157894736842105, 'recall': 0.2727272727272727, 'f1-score': 0.2926829268292683, 'support': 22}, '3': {'precision': 0.6923076923076923, 'recall': 0.42857142857142855, 'f1-score': 0.5294117647058824, 'support': 21}, '4': {'precision': 0.3888888888888889, 'recall': 0.3888888888888889, 'f1-score': 0.3888888888888889, 'support': 18}, '5': {'precision': 0.35714285714285715, 'recall': 0.5, 'f1-score': 0.41666666666666663, 'support': 20}, '6': {'precision': 0.18181818181818182, 'recall': 0.09523809523809523, 'f1-score': 0.125, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.6391304347826087, 'recall': 0.8352272727272727, 'f1-score': 0.7241379310344828, 'support': 176

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 51.64179104477612
{'0': {'precision': 0.42857142857142855, 'recall': 0.15789473684210525, 'f1-score': 0.23076923076923078, 'support': 19}, '1': {'precision': 0.7222222222222222, 'recall': 0.7222222222222222, 'f1-score': 0.7222222222222222, 'support': 18}, '2': {'precision': 0.5384615384615384, 'recall': 0.3181818181818182, 'f1-score': 0.39999999999999997, 'support': 22}, '3': {'precision': 0.65, 'recall': 0.6190476190476191, 'f1-score': 0.6341463414634146, 'support': 21}, '4': {'precision': 0.39285714285714285, 'recall': 0.6111111111111112, 'f1-score': 0.4782608695652174, 'support': 18}, '5': {'precision': 0.5555555555555556, 'recall': 0.75, 'f1-score': 0.6382978723404256, 'support': 20}, '6': {'precision': 0.21951219512195122, 'recall': 0.8571428571428571, 'f1-score': 0.3495145631067961, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.6642857142857143, 'recall': 0.5284090909090909, 'f1-score': 0.5886075949367089, '

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 54.328358208955216
{'0': {'precision': 0.42857142857142855, 'recall': 0.15789473684210525, 'f1-score': 0.23076923076923078, 'support': 19}, '1': {'precision': 0.6875, 'recall': 0.6111111111111112, 'f1-score': 0.6470588235294118, 'support': 18}, '2': {'precision': 0.2631578947368421, 'recall': 0.22727272727272727, 'f1-score': 0.24390243902439024, 'support': 22}, '3': {'precision': 0.5357142857142857, 'recall': 0.7142857142857143, 'f1-score': 0.6122448979591837, 'support': 21}, '4': {'precision': 0.6666666666666666, 'recall': 0.6666666666666666, 'f1-score': 0.6666666666666666, 'support': 18}, '5': {'precision': 0.6666666666666666, 'recall': 0.5, 'f1-score': 0.5714285714285715, 'support': 20}, '6': {'precision': 0.25, 'recall': 0.7619047619047619, 'f1-score': 0.3764705882352941, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.6547619047619048, 'recall': 0.625, 'f1-score': 0.6395348837209303, 'support': 176}, 'accuracy'

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and 

Accuracy: 54.328358208955216
{'0': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 19}, '1': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 18}, '2': {'precision': 1.0, 'recall': 0.09090909090909091, 'f1-score': 0.16666666666666669, 'support': 22}, '3': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 21}, '4': {'precision': 0.6666666666666666, 'recall': 0.1111111111111111, 'f1-score': 0.1904761904761905, 'support': 18}, '5': {'precision': 1.0, 'recall': 0.1, 'f1-score': 0.18181818181818182, 'support': 20}, '6': {'precision': 0.3333333333333333, 'recall': 0.047619047619047616, 'f1-score': 0.08333333333333333, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.5401234567901234, 'recall': 0.9943181818181818, 'f1-score': 0.7, 'support': 176}, 'accuracy': 0.5432835820895522, 'macro avg': {'precision': 0.39334705075445814, 'recall': 0.14932860349527016, 'f1-score': 0.14692159692159693, 'suppo

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and 

Accuracy: 55.52238805970149
{'0': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 19}, '1': {'precision': 0.75, 'recall': 0.16666666666666666, 'f1-score': 0.27272727272727276, 'support': 18}, '2': {'precision': 0.2857142857142857, 'recall': 0.09090909090909091, 'f1-score': 0.13793103448275862, 'support': 22}, '3': {'precision': 0.5714285714285714, 'recall': 0.19047619047619047, 'f1-score': 0.2857142857142857, 'support': 21}, '4': {'precision': 0.46153846153846156, 'recall': 0.3333333333333333, 'f1-score': 0.3870967741935484, 'support': 18}, '5': {'precision': 0.8, 'recall': 0.2, 'f1-score': 0.32000000000000006, 'support': 20}, '6': {'precision': 0.2608695652173913, 'recall': 0.2857142857142857, 'f1-score': 0.2727272727272727, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.5833333333333334, 'recall': 0.9147727272727273, 'f1-score': 0.7123893805309736, 'support': 176}, 'accuracy': 0.5552238805970149, 'macro avg':

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 50.14925373134328
{'0': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 19}, '1': {'precision': 0.5, 'recall': 0.1111111111111111, 'f1-score': 0.1818181818181818, 'support': 18}, '2': {'precision': 0.2222222222222222, 'recall': 0.09090909090909091, 'f1-score': 0.1290322580645161, 'support': 22}, '3': {'precision': 0.3, 'recall': 0.14285714285714285, 'f1-score': 0.19354838709677416, 'support': 21}, '4': {'precision': 0.16666666666666666, 'recall': 0.3333333333333333, 'f1-score': 0.2222222222222222, 'support': 18}, '5': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '6': {'precision': 0.4, 'recall': 0.09523809523809523, 'f1-score': 0.15384615384615385, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.5687732342007435, 'recall': 0.8693181818181818, 'f1-score': 0.6876404494382022, 'support': 176}, 'accuracy': 0.5014925373134328, 'macro avg': {'precision': 0.23974023589884805, 'recall': 0

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 49.55223880597015
{'0': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 19}, '1': {'precision': 0.6666666666666666, 'recall': 0.1111111111111111, 'f1-score': 0.1904761904761905, 'support': 18}, '2': {'precision': 0.3333333333333333, 'recall': 0.045454545454545456, 'f1-score': 0.08, 'support': 22}, '3': {'precision': 0.2857142857142857, 'recall': 0.09523809523809523, 'f1-score': 0.14285714285714285, 'support': 21}, '4': {'precision': 0.10526315789473684, 'recall': 0.2222222222222222, 'f1-score': 0.14285714285714285, 'support': 18}, '5': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '6': {'precision': 0.2222222222222222, 'recall': 0.09523809523809523, 'f1-score': 0.13333333333333333, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.5656934306569343, 'recall': 0.8806818181818182, 'f1-score': 0.688888888888889, 'support': 176}, 'accuracy': 0.4955223880597015, 'macro avg': {'precision': 

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 55.52238805970149
{'0': {'precision': 1.0, 'recall': 0.10526315789473684, 'f1-score': 0.1904761904761905, 'support': 19}, '1': {'precision': 0.8, 'recall': 0.4444444444444444, 'f1-score': 0.5714285714285714, 'support': 18}, '2': {'precision': 0.4, 'recall': 0.09090909090909091, 'f1-score': 0.14814814814814814, 'support': 22}, '3': {'precision': 0.5, 'recall': 0.2857142857142857, 'f1-score': 0.36363636363636365, 'support': 21}, '4': {'precision': 0.5384615384615384, 'recall': 0.3888888888888889, 'f1-score': 0.45161290322580644, 'support': 18}, '5': {'precision': 0.75, 'recall': 0.15, 'f1-score': 0.24999999999999997, 'support': 20}, '6': {'precision': 0.1875, 'recall': 0.14285714285714285, 'f1-score': 0.16216216216216214, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.5677655677655677, 'recall': 0.8806818181818182, 'f1-score': 0.690423162583519, 'support': 176}, 'accuracy': 0.5552238805970149, 'macro avg': {'precisio

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 57.611940298507456
{'0': {'precision': 0.5, 'recall': 0.10526315789473684, 'f1-score': 0.17391304347826086, 'support': 19}, '1': {'precision': 0.6818181818181818, 'recall': 0.8333333333333334, 'f1-score': 0.7499999999999999, 'support': 18}, '2': {'precision': 0.5, 'recall': 0.2727272727272727, 'f1-score': 0.3529411764705882, 'support': 22}, '3': {'precision': 0.6875, 'recall': 0.5238095238095238, 'f1-score': 0.5945945945945946, 'support': 21}, '4': {'precision': 0.7083333333333334, 'recall': 0.9444444444444444, 'f1-score': 0.8095238095238096, 'support': 18}, '5': {'precision': 0.6666666666666666, 'recall': 0.6, 'f1-score': 0.631578947368421, 'support': 20}, '6': {'precision': 0.25, 'recall': 0.9523809523809523, 'f1-score': 0.39603960396039606, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.6918238993710691, 'recall': 0.625, 'f1-score': 0.6567164179104478, 'support': 176}, 'accuracy': 0.5761194029850746, 'macro avg'

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 54.62686567164179
{'0': {'precision': 0.42857142857142855, 'recall': 0.15789473684210525, 'f1-score': 0.23076923076923078, 'support': 19}, '1': {'precision': 0.7647058823529411, 'recall': 0.7222222222222222, 'f1-score': 0.7428571428571428, 'support': 18}, '2': {'precision': 0.36363636363636365, 'recall': 0.18181818181818182, 'f1-score': 0.24242424242424246, 'support': 22}, '3': {'precision': 0.6470588235294118, 'recall': 0.5238095238095238, 'f1-score': 0.5789473684210527, 'support': 21}, '4': {'precision': 0.6538461538461539, 'recall': 0.9444444444444444, 'f1-score': 0.7727272727272727, 'support': 18}, '5': {'precision': 0.6923076923076923, 'recall': 0.45, 'f1-score': 0.5454545454545455, 'support': 20}, '6': {'precision': 0.2289156626506024, 'recall': 0.9047619047619048, 'f1-score': 0.36538461538461536, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.6645962732919255, 'recall': 0.6079545454545454, 'f1-score': 0.6350

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 54.62686567164179
{'0': {'precision': 1.0, 'recall': 0.10526315789473684, 'f1-score': 0.1904761904761905, 'support': 19}, '1': {'precision': 0.6, 'recall': 0.5, 'f1-score': 0.5454545454545454, 'support': 18}, '2': {'precision': 0.5, 'recall': 0.3181818181818182, 'f1-score': 0.3888888888888889, 'support': 22}, '3': {'precision': 0.5263157894736842, 'recall': 0.47619047619047616, 'f1-score': 0.5, 'support': 21}, '4': {'precision': 0.4583333333333333, 'recall': 0.6111111111111112, 'f1-score': 0.5238095238095238, 'support': 18}, '5': {'precision': 1.0, 'recall': 0.1, 'f1-score': 0.18181818181818182, 'support': 20}, '6': {'precision': 0.1794871794871795, 'recall': 0.3333333333333333, 'f1-score': 0.23333333333333334, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.6136363636363636, 'recall': 0.7670454545454546, 'f1-score': 0.6818181818181818, 'support': 176}, 'accuracy': 0.5462686567164179, 'macro avg': {'precision': 0.54

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 52.23880597014925
{'0': {'precision': 0.3333333333333333, 'recall': 0.05263157894736842, 'f1-score': 0.09090909090909091, 'support': 19}, '1': {'precision': 0.8571428571428571, 'recall': 0.3333333333333333, 'f1-score': 0.48, 'support': 18}, '2': {'precision': 0.4444444444444444, 'recall': 0.18181818181818182, 'f1-score': 0.2580645161290322, 'support': 22}, '3': {'precision': 0.6428571428571429, 'recall': 0.42857142857142855, 'f1-score': 0.5142857142857143, 'support': 21}, '4': {'precision': 0.5, 'recall': 0.5, 'f1-score': 0.5, 'support': 18}, '5': {'precision': 0.5, 'recall': 0.1, 'f1-score': 0.16666666666666669, 'support': 20}, '6': {'precision': 0.20408163265306123, 'recall': 0.47619047619047616, 'f1-score': 0.2857142857142857, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.5800865800865801, 'recall': 0.7613636363636364, 'f1-score': 0.6584766584766585, 'support': 176}, 'accuracy': 0.5223880597014925, 'macro avg':

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and 

Accuracy: 60.0
{'0': {'precision': 1.0, 'recall': 0.15789473684210525, 'f1-score': 0.2727272727272727, 'support': 19}, '1': {'precision': 1.0, 'recall': 0.1111111111111111, 'f1-score': 0.19999999999999998, 'support': 18}, '2': {'precision': 0.8571428571428571, 'recall': 0.2727272727272727, 'f1-score': 0.41379310344827586, 'support': 22}, '3': {'precision': 0.6, 'recall': 0.2857142857142857, 'f1-score': 0.3870967741935483, 'support': 21}, '4': {'precision': 0.7777777777777778, 'recall': 0.3888888888888889, 'f1-score': 0.5185185185185185, 'support': 18}, '5': {'precision': 0.6666666666666666, 'recall': 0.2, 'f1-score': 0.30769230769230765, 'support': 20}, '6': {'precision': 0.375, 'recall': 0.2857142857142857, 'f1-score': 0.3243243243243243, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.5921985815602837, 'recall': 0.9488636363636364, 'f1-score': 0.7292576419213974, 'support': 176}, 'accuracy': 0.6, 'macro avg': {'precision': 

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Accuracy: 58.507462686567166
{'0': {'precision': 1.0, 'recall': 0.15789473684210525, 'f1-score': 0.2727272727272727, 'support': 19}, '1': {'precision': 0.5454545454545454, 'recall': 0.3333333333333333, 'f1-score': 0.41379310344827586, 'support': 18}, '2': {'precision': 0.4666666666666667, 'recall': 0.3181818181818182, 'f1-score': 0.3783783783783784, 'support': 22}, '3': {'precision': 0.5714285714285714, 'recall': 0.5714285714285714, 'f1-score': 0.5714285714285714, 'support': 21}, '4': {'precision': 0.6428571428571429, 'recall': 0.5, 'f1-score': 0.5625000000000001, 'support': 18}, '5': {'precision': 0.6428571428571429, 'recall': 0.45, 'f1-score': 0.5294117647058824, 'support': 20}, '6': {'precision': 0.2702702702702703, 'recall': 0.47619047619047616, 'f1-score': 0.3448275862068966, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.6511627906976745, 'recall': 0.7954545454545454, 'f1-score': 0.7161125319693095, 'support': 176}, 'a

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 49.25373134328358
{'0': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 19}, '1': {'precision': 0.75, 'recall': 0.3333333333333333, 'f1-score': 0.46153846153846156, 'support': 18}, '2': {'precision': 0.14285714285714285, 'recall': 0.045454545454545456, 'f1-score': 0.06896551724137931, 'support': 22}, '3': {'precision': 0.14285714285714285, 'recall': 0.047619047619047616, 'f1-score': 0.07142857142857142, 'support': 21}, '4': {'precision': 0.17391304347826086, 'recall': 0.2222222222222222, 'f1-score': 0.1951219512195122, 'support': 18}, '5': {'precision': 0.3333333333333333, 'recall': 0.05, 'f1-score': 0.08695652173913045, 'support': 20}, '6': {'precision': 0.25, 'recall': 0.047619047619047616, 'f1-score': 0.08, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.5354609929078015, 'recall': 0.8579545454545454, 'f1-score': 0.6593886462882097, 'support': 176}, 'accuracy': 0.4925373134328358, 'macro avg': {'pre

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 51.04477611940299
{'0': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 19}, '1': {'precision': 0.8571428571428571, 'recall': 0.3333333333333333, 'f1-score': 0.48, 'support': 18}, '2': {'precision': 0.4, 'recall': 0.09090909090909091, 'f1-score': 0.14814814814814814, 'support': 22}, '3': {'precision': 0.14285714285714285, 'recall': 0.047619047619047616, 'f1-score': 0.07142857142857142, 'support': 21}, '4': {'precision': 0.16666666666666666, 'recall': 0.16666666666666666, 'f1-score': 0.16666666666666666, 'support': 18}, '5': {'precision': 0.5, 'recall': 0.05, 'f1-score': 0.09090909090909091, 'support': 20}, '6': {'precision': 0.5, 'recall': 0.047619047619047616, 'f1-score': 0.08695652173913042, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.5376712328767124, 'recall': 0.8920454545454546, 'f1-score': 0.670940170940171, 'support': 176}, 'accuracy': 0.5104477611940299, 'macro avg': {'precision': 0.3449264

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and 

Accuracy: 56.11940298507463
{'0': {'precision': 1.0, 'recall': 0.10526315789473684, 'f1-score': 0.1904761904761905, 'support': 19}, '1': {'precision': 1.0, 'recall': 0.16666666666666666, 'f1-score': 0.2857142857142857, 'support': 18}, '2': {'precision': 1.0, 'recall': 0.13636363636363635, 'f1-score': 0.24000000000000002, 'support': 22}, '3': {'precision': 0.5, 'recall': 0.09523809523809523, 'f1-score': 0.16, 'support': 21}, '4': {'precision': 0.7142857142857143, 'recall': 0.2777777777777778, 'f1-score': 0.4, 'support': 18}, '5': {'precision': 1.0, 'recall': 0.1, 'f1-score': 0.18181818181818182, 'support': 20}, '6': {'precision': 0.14285714285714285, 'recall': 0.047619047619047616, 'f1-score': 0.07142857142857142, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.5537459283387622, 'recall': 0.9659090909090909, 'f1-score': 0.7039337474120083, 'support': 176}, 'accuracy': 0.5611940298507463, 'macro avg': {'precision': 0.6567654206

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Accuracy: 58.507462686567166
{'0': {'precision': 1.0, 'recall': 0.05263157894736842, 'f1-score': 0.1, 'support': 19}, '1': {'precision': 0.5454545454545454, 'recall': 0.3333333333333333, 'f1-score': 0.41379310344827586, 'support': 18}, '2': {'precision': 0.5384615384615384, 'recall': 0.3181818181818182, 'f1-score': 0.39999999999999997, 'support': 22}, '3': {'precision': 0.75, 'recall': 0.42857142857142855, 'f1-score': 0.5454545454545454, 'support': 21}, '4': {'precision': 0.5333333333333333, 'recall': 0.4444444444444444, 'f1-score': 0.4848484848484848, 'support': 18}, '5': {'precision': 0.6153846153846154, 'recall': 0.4, 'f1-score': 0.4848484848484849, 'support': 20}, '6': {'precision': 0.30303030303030304, 'recall': 0.47619047619047616, 'f1-score': 0.37037037037037035, 'support': 21}, '7': {'precision': 0.25, 'recall': 0.05, 'f1-score': 0.08333333333333334, 'support': 20}, '8': {'precision': 0.6266094420600858, 'recall': 0.8295454545454546, 'f1-score': 0.7139364303178485, 'support': 1

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-p

Accuracy: 58.2089552238806
{'0': {'precision': 0.5, 'recall': 0.10526315789473684, 'f1-score': 0.17391304347826086, 'support': 19}, '1': {'precision': 0.6818181818181818, 'recall': 0.8333333333333334, 'f1-score': 0.7499999999999999, 'support': 18}, '2': {'precision': 0.34615384615384615, 'recall': 0.4090909090909091, 'f1-score': 0.37500000000000006, 'support': 22}, '3': {'precision': 0.7058823529411765, 'recall': 0.5714285714285714, 'f1-score': 0.6315789473684211, 'support': 21}, '4': {'precision': 0.6296296296296297, 'recall': 0.9444444444444444, 'f1-score': 0.7555555555555556, 'support': 18}, '5': {'precision': 0.5909090909090909, 'recall': 0.65, 'f1-score': 0.6190476190476191, 'support': 20}, '6': {'precision': 0.2714285714285714, 'recall': 0.9047619047619048, 'f1-score': 0.41758241758241754, 'support': 21}, '7': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 20}, '8': {'precision': 0.7346938775510204, 'recall': 0.6136363636363636, 'f1-score': 0.6687306501547988, 'sup

In [16]:
with open('model_results.pkl', 'wb+') as f:
    pickle.dump(results, f)

In [12]:
from typing import List
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, balanced_accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from HateSpeechClassifier import TARGET_TO_INDEX, TARGET_TYPES
def run_tests(texts: List[str], labels: List[int], model_names: List[str], debug=True) -> dict:
    '''
    Get metrics for multiple embedding/model combos. 
    Assumes these models are already saved.
    texts and labels are unseen.
    No training is done.

    params:
        texts: list of strings (posts), already stripped of punctuation/symbols
        labels: class labels
        model_names: filenames of saved models to test; assumes these are in MODELS_PATH
    
    returns: dictionary of results:
        {'model_name': {
            'report': classification report,
            'accuracy': test accuracy,
            'confusion' : confusion matrix
            }
        }
    '''
    results = {}
    for model_name in model_names:
        if debug:
            print('----------------------------------------')
            print(model_name)

        # classify given texts with current model
        predicted_labels, predicted_probs = classify(texts, model_name)
        predicted_labels = [TARGET_TO_INDEX[target] for target in predicted_labels]
        
        # get classification report, test accuracy, confusion matrix
        report = classification_report(labels, predicted_labels, output_dict=True)
        accuracy = accuracy_score(labels, predicted_labels)
        balanced_accuracy = balanced_accuracy_score(labels, predicted_labels)
        precision = precision_score(labels, predicted_labels, average='weighted')
        recall = recall_score(labels, predicted_labels, average='weighted') 
        f1 = f1_score(labels, predicted_labels, average='weighted') 
        #roc_auc = roc_auc_score(labels, predicted_labels, multi_class='ovr')
        
        confusion = confusion_matrix(labels, predicted_labels)

        if debug:
            print(f'Accuracy: {accuracy * 100}')
            print(report)
            print(confusion)

        results[model_name] = {
            'report': report,
            'accuracy': accuracy,
            'balanced accuracy': balanced_accuracy,
            'precision': precision,
            'recall': recall,
            'f1': f1,
            #'roc_auc': roc_auc,
            'confusion' : confusion
        }
    
    return results

In [13]:
from nltk.corpus import stopwords
from typing import Tuple
from HateSpeechClassifier import utils_preprocess_text, Model, Embedding
def classify(texts: List[str], model_path: str) -> Tuple[List[str], List[float]]:
    '''
    Classify unseen text

    params:
        texts: list of strings (social media posts)
        model_path: string, path to saved model to use for classification

    returns: parallel lists of predicted classes, predicted probabilites
    '''
    filename = model_path.split('/')[-1]
    model_name, *embedding_params = filename.split('_')
    embedding_filename = '_'.join(param for param in embedding_params)
    embedding_type = embedding_params[0]

    if filename.endswith('nostop'):
        stop_words = stopwords.words('english')
    else:
        stop_words = None
    
    # preprocess input
    texts = [utils_preprocess_text(text, lst_stopwords=stop_words) for text in texts]

    # transform input text into embedding
    embedding = Embedding(embedding_type, load_filename=embedding_filename)
    vectorized_texts = embedding.vectorize(texts, unseen=True)

    # predict
    full_model_name = model_name + '_' + embedding_filename
    model = Model(model_name, load_filename=full_model_name, max_iter=2000) 
    probabilities = model.model.predict_proba(vectorized_texts)
    print('probabilities len:', len(probabilities))
    
    # return classes with highest probs for each text
    predicted_classes = [0] * len(texts)
    predicted_probs = [0] * len(texts)

    for i, probs in enumerate(probabilities):
        print('  i, probs:', i, probs)
        max_prob = max(probs)
        print('  max prob:', max_prob)
        max_class = np.where(probs == max_prob)[0][0]
        predicted_classes[i] = TARGET_TYPES[max_class]
        predicted_probs[i] = max_prob

    return predicted_classes, predicted_probs

In [14]:
test_report = run_tests(X_test, y_test, ['DT_glove_300dim_tfidfweight_nostop'])

----------------------------------------
DT_glove_300dim_tfidfweight_nostop
probabilities len: 9166
  i, probs: 0 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
  max prob: 1.0
  i, probs: 1 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
  max prob: 1.0
  i, probs: 2 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
  max prob: 1.0
  i, probs: 3 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
  max prob: 1.0
  i, probs: 4 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
  max prob: 1.0
  i, probs: 5 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  max prob: 1.0
  i, probs: 6 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
  max prob: 1.0
  i, probs: 7 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
  max prob: 1.0
  i, probs: 8 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  max prob: 1.0
  i, probs: 9 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  max prob: 1.0
  i, probs: 10 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  max prob: 1.0
  i, probs: 11 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
  max prob: 1.0
  i, probs: 12 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
  max prob: 1.0
  i, probs: 13 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  max prob: 1.0
  i, probs: 14 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
  max prob: 1.0
  i, probs

IndexError: list assignment index out of range

In [20]:
with open('Reports/d2v_and_tfidf_tests', 'wb+') as f:
    pickle.dump(results, f)

In [21]:
new_results = {}
for model_name in results:
    accuracy = results[model_name]['accuracy']
    balanced = results[model_name]['balanced accuracy']
    precision = results[model_name]['precision']
    recall = results[model_name]['recall']
    f1 = results[model_name]['f1']

    new_results[model_name] = {
        'accuracy': accuracy,
        'balanced_accuracy': balanced,
        'precision': precision,
        'recall': recall,
        'f1': f1
    }

In [26]:
results_df = pd.DataFrame(new_results).T

In [28]:
results_df.to_excel('Reports/tfidf_and_d2v.xlsx')

##### Classifying Reddit and Tumblr Datasets

In [20]:
texts = ["Happy birthday bird! @codyflitcraft",
    "Haha, Yankees fans are bent out of shape about the Hu27le graphic",
    "Maybe the UN could talk to those asian and african nations responsible for 90%+ of the pollution in the oceans' instead of insisting on this bullshit about climate change. ",
    "Jews are a separate ethnicity, a danger to national security, and should be banned.",
    "Gay men are a danger to children.",
    "We are being invaded, We must fight until we will vanquish immigrants.",
    "Muslims are not welcome in our country. They have nothing to contribute to our society.",
    "black folks all act bad",
    "Women are only useful as housekeepers.",
    "The disabled should not to be allowed to vote."]
classes = [8,8,7,1,2,3,4,5,6,0]

In [16]:
model_names = ['LR_tfidf_matrix_nostop','LR_w2v_equalweight_nostop']

In [21]:
results = HateSpeechClassifier.run_tests(texts, classes, model_names)

----------------------------------------
LR_tfidf_matrix_nostop
Accuracy: 90.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       0.00      0.00      0.00         1
           8       0.67      1.00      0.80         2

    accuracy                           0.90        10
   macro avg       0.85      0.89      0.87        10
weighted avg       0.83      0.90      0.86        10

[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 2]]
--------------------------

/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/marisa/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Accuracy: 100.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         1
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         1
           8       1.00      1.00      1.00         2

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10

[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 2]]


In [ ]:
results